#! /bin/sh

#sxhkd &

bspc monitor VGA-1 -d I II III IV
bspc monitor VGA-2 -d V VI VII
bspc monitor VGA-3 -d VIII IX X


bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a URxvt:launcher state=floating

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
